export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';
export const GET_TODOS_DONE = 'GET_TODOS_DONE';

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_DONE = 'ADD_TODO_DONE';

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_DONE = 'DELETE_TODO_DONE';

export const COMPLETED_TODO_REQUEST = 'COMPLETED_TODO_REQUEST';
export const COMPLETED_TODO_DONE = 'COMPLETED_TODO_DONE';

export const EDIT_TODO_REQUEST = 'EDIT_TODO_REQUEST';
export const EDIT_TODO_DONE = 'EDIT_TODO_DONE';

// isActive todo
export const SELECT_TODO = 'SELECT_TODO';
export const UNSELECT_TODO = 'UNSELECT_TODO';
